//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidoresModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class lectura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lectura()
        {
            this.medidores = new HashSet<medidore>();
        }
    
        public int id { get; set; }
        public string numeroLec { get; set; }
        public string fechaLec { get; set; }
        public string horaLec { get; set; }
        public string minutoLec { get; set; }
        public string consumoLec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medidore> medidores { get; set; }
    }
}
